# permissions for end users to edit postgres.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: postgresql-operator
    app.kubernetes.io/managed-by: kustomize
  name: postgres-editor-role
rules:
- apiGroups:
  - postgres.snappcloud.io
  resources:
  - postgres
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.snappcloud.io
  resources:
  - postgres/status
  verbs:
  - get
